import smtplib
import logging
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime
from typing import Optional

from ..config import settings

logger = logging.getLogger(__name__)


class EmailService:
    def send_report(
        self,
        to_email: str,
        subject: str,
        report_text: str,
    ) -> bool:
        """Send AI-generated report via Gmail SMTP."""
        try:
            msg = MIMEMultipart("alternative")
            msg["From"] = f"Sales AI Report <{settings.SMTP_USER}>"
            msg["To"] = to_email
            msg["Subject"] = subject

            # Plain text version
            msg.attach(MIMEText(report_text, "plain", "utf-8"))

            # HTML version
            html_body = self._build_html(subject, report_text)
            msg.attach(MIMEText(html_body, "html", "utf-8"))

            with smtplib.SMTP(settings.SMTP_HOST, settings.SMTP_PORT) as server:
                server.starttls()
                server.login(settings.SMTP_USER, settings.SMTP_PASSWORD)
                server.send_message(msg)

            logger.info(f"Report email sent to {to_email}")
            return True
        except Exception as e:
            logger.error(f"Email send error: {e}", exc_info=True)
            return False

    def _build_html(self, subject: str, report_text: str) -> str:
        now = datetime.now().strftime("%d/%m/%Y %H:%M")
        # Convert bullet points and newlines to HTML
        lines = report_text.split("\n")
        html_lines = []
        for line in lines:
            stripped = line.strip()
            if not stripped:
                html_lines.append("<br/>")
            elif stripped.startswith("•") or stripped.startswith("-"):
                html_lines.append(f"<li style='margin-bottom:4px'>{stripped.lstrip('•- ')}</li>")
            elif stripped.startswith("===") or stripped.startswith("---"):
                title = stripped.strip("=- ")
                html_lines.append(f"<h3 style='color:#1e40af;margin:16px 0 8px 0;font-size:15px'>{title}</h3>")
            else:
                html_lines.append(f"<p style='margin:4px 0'>{stripped}</p>")

        body_html = "\n".join(html_lines)

        return f"""<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="font-family:'Segoe UI',Tahoma,sans-serif;background:#f8fafc;padding:24px">
  <div style="max-width:640px;margin:0 auto;background:#fff;border-radius:12px;overflow:hidden;box-shadow:0 1px 3px rgba(0,0,0,0.1)">
    <div style="background:linear-gradient(135deg,#1e40af,#4f46e5);padding:24px 32px">
      <h1 style="color:#fff;margin:0;font-size:20px">{subject}</h1>
      <p style="color:#bfdbfe;margin:4px 0 0 0;font-size:13px">Generated by Gemini AI | {now}</p>
    </div>
    <div style="padding:24px 32px;color:#334155;font-size:14px;line-height:1.7">
      {body_html}
    </div>
    <div style="padding:16px 32px;background:#f1f5f9;border-top:1px solid #e2e8f0;text-align:center">
      <p style="color:#94a3b8;font-size:11px;margin:0">Sales AI Report | Powered by Gemini 2.5 Flash Lite</p>
    </div>
  </div>
</body>
</html>"""


email_service = EmailService()
