#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Run from anywhere: values land in the repo's .env (gitignored).
cd "$(dirname "$0")/.."
ENV_FILE="${ENV_FILE:-.env}"

TOTAL_STAGES=6
PROFILE="demand"
REGION="ap-southeast-1"
ISSUE=2   # GitHub issue "Account prerequisites"

banner "AWS account prerequisites (ticket #$ISSUE)"

# ── 1 ────────────────────────────────────────────────────────────────────
stage "IAM — access key for your existing user"
say "Reuse your Tenant-office IAM user. Make a NEW access key just for this project;"
say "you will delete it after the AWS foundation ticket (Render gets its own, narrower key)."
KEEP_KEY=0
if aws sts get-caller-identity --profile "$PROFILE" >/dev/null 2>&1; then
  note "profile '$PROFILE' already works on this machine"
  if confirm "Keep the existing key for profile '$PROFILE'?"; then KEEP_KEY=1; fi
fi
if (( KEEP_KEY )); then
  aws configure set region "$REGION" --profile "$PROFILE"
  aws configure set output json --profile "$PROFILE"
  write_env AWS_PROFILE "$PROFILE"
  write_env AWS_REGION "$REGION"
else
open_url "https://console.aws.amazon.com/iam/home#/users"
step "Click your user → tab 'Security credentials' → 'Create access key'."
step "Use case: 'Command Line Interface (CLI)' → tick the confirmation → Next → Create."
step "Copy both values now; the secret is shown only once."
ask AWS_ACCESS_KEY_ID_DEMAND "Paste the Access key ID:"
ask_secret AWS_SECRET_ACCESS_KEY_DEMAND "Paste the Secret access key:"
# Pasting in Git Bash with Ctrl+V inserts a literal control character (^V) instead of pasting, and Windows
# paste can add a carriage return or spaces; any of those corrupts the signed request (STS answers 400 with no body).
note "paste with right-click or Shift+Insert — Ctrl+V does not paste in this terminal"
AWS_ACCESS_KEY_ID_DEMAND=$(printf '%s' "$AWS_ACCESS_KEY_ID_DEMAND" | tr -d '[:cntrl:][:space:]')
AWS_SECRET_ACCESS_KEY_DEMAND=$(printf '%s' "$AWS_SECRET_ACCESS_KEY_DEMAND" | tr -d '[:cntrl:][:space:]')
if [[ -z "$AWS_ACCESS_KEY_ID_DEMAND" || -z "$AWS_SECRET_ACCESS_KEY_DEMAND" ]]; then
  warn "both values are required"; exit 1
fi
if [[ ! "$AWS_ACCESS_KEY_ID_DEMAND" =~ ^[A-Z0-9]{16,32}$ || ${#AWS_SECRET_ACCESS_KEY_DEMAND} -lt 30 ]]; then
  warn "that does not look like an AWS key pair (ID is ~20 upper-case chars, secret ~40 chars) — check the paste"; exit 1
fi
aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID_DEMAND" --profile "$PROFILE"
aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY_DEMAND" --profile "$PROFILE"
aws configure set region "$REGION" --profile "$PROFILE"
aws configure set output json --profile "$PROFILE"
note "stored in ~/.aws/credentials under profile '$PROFILE' (never in the repo)"
write_env AWS_PROFILE "$PROFILE"
write_env AWS_REGION "$REGION"
fi

# ── 2 ────────────────────────────────────────────────────────────────────
stage "Verify the profile"
say "Asking AWS who this key belongs to..."
if ! IDENTITY=$(aws sts get-caller-identity --profile "$PROFILE" --output json 2>&1); then
  warn "the key was rejected:"; note "$IDENTITY"
  warn "re-run the wizard and paste the key again (check for stray spaces)"; exit 1
fi
ACCOUNT_ID=$(printf '%s' "$IDENTITY" | python -c "import json,sys; print(json.load(sys.stdin)['Account'])")
USER_ARN=$(printf '%s' "$IDENTITY" | python -c "import json,sys; print(json.load(sys.stdin)['Arn'])")
USER_NAME="${USER_ARN##*/}"
printf '  %s✓%s account %s, user %s\n' "$GREEN" "$RESET" "$ACCOUNT_ID" "$USER_NAME"
write_env AWS_ACCOUNT_ID "$ACCOUNT_ID"
pause

# ── 3 ────────────────────────────────────────────────────────────────────
stage "Check this user can provision"
say "The AWS foundation ticket needs S3, DynamoDB, SageMaker, IAM and Budgets rights."
NEEDED="AdministratorAccess AmazonS3FullAccess AmazonDynamoDBFullAccess AmazonSageMakerFullAccess IAMFullAccess AWSBudgetsActionsWithAWSResourceControlAccess"
ATTACHED=""
if [[ "$USER_ARN" == *":user/"* ]]; then
  ATTACHED=$(aws iam list-attached-user-policies --user-name "$USER_NAME" --profile "$PROFILE" \
    --query 'AttachedPolicies[].PolicyName' --output text 2>/dev/null || true)
  for g in $(aws iam list-groups-for-user --user-name "$USER_NAME" --profile "$PROFILE" --query 'Groups[].GroupName' --output text 2>/dev/null || true); do
    ATTACHED="$ATTACHED $(aws iam list-attached-group-policies --group-name "$g" --profile "$PROFILE" --query 'AttachedPolicies[].PolicyName' --output text 2>/dev/null || true)"
  done
fi
if [[ -z "$ATTACHED" ]]; then
  warn "could not list this user's policies (no iam:List* permission, or a role/SSO identity)."
  warn "Ask your AWS admin to confirm the user has AdministratorAccess or the five policies below,"
  warn "then continue — the foundation ticket will fail loudly if something is missing."
  note "$NEEDED"
elif [[ " $ATTACHED " == *" AdministratorAccess "* ]]; then
  printf '  %s✓%s AdministratorAccess is attached — everything the foundation ticket needs\n' "$GREEN" "$RESET"
else
  MISSING=""
  for p in AmazonS3FullAccess AmazonDynamoDBFullAccess AmazonSageMakerFullAccess IAMFullAccess AWSBudgetsActionsWithAWSResourceControlAccess; do
    [[ " $ATTACHED " == *" $p "* ]] || MISSING="$MISSING $p"
  done
  if [[ -z "$MISSING" ]]; then
    printf '  %s✓%s all five provisioning policies are attached\n' "$GREEN" "$RESET"
  else
    warn "missing policies:$MISSING"
    open_url "https://console.aws.amazon.com/iam/home#/users/details/${USER_NAME}?section=permissions"
    step "Add permissions → Attach policies directly → tick the missing ones → Add permissions."
    step "(If you cannot, ask your AWS admin — then re-run this wizard.)"
    pause "Attached them? Press Enter to continue (or Ctrl-C to stop here)"
  fi
fi
pause

# ── 4 ────────────────────────────────────────────────────────────────────
stage "Bedrock — model access for Claude in $REGION"
say "The AI pages will call Claude Haiku 4.5, Sonnet 5 and Opus 5 through Amazon Bedrock."
say "Anthropic models need a one-time use-case form per account; some accounts also need"
say "'Modify model access'. The console wording changes often — the real check is below."
open_url "https://${REGION}.console.aws.amazon.com/bedrock/home?region=${REGION}#/modelaccess"
step "If you see 'Modify model access' / 'Enable specific models': select the three Anthropic Claude"
step "  models (Haiku 4.5, Sonnet 5, Opus 5) → Next → fill the use-case form → Submit."
step "If the page says access is granted by default: open any Claude model's page and submit the"
step "  Anthropic use-case form if it is offered (company: yours; use case: internal demand-forecasting demo)."
step "Wait until the status reads 'Access granted' (usually immediate, sometimes a few minutes)."
pause "Done in the console? Press Enter to verify with real calls"

say "Looking up Claude model IDs available in $REGION..."
IDS=$( { aws bedrock list-inference-profiles --profile "$PROFILE" --region "$REGION" --query 'inferenceProfileSummaries[].inferenceProfileId' --output text 2>/dev/null; \
         aws bedrock list-foundation-models --profile "$PROFILE" --region "$REGION" --by-provider Anthropic --query 'modelSummaries[].modelId' --output text 2>/dev/null; } | tr '\t' '\n' | sort -u )
GRANTED=""
for want in "claude-haiku-4-5" "claude-sonnet-5" "claude-opus-5"; do
  # newer Claude models need an inference-profile ID for on-demand calls: prefer apac., then global., then the bare model ID
  candidate=""
  for prefix in "apac\." "global\." "anthropic\."; do
    candidate=$(printf '%s\n' "$IDS" | grep -E "^${prefix}.*${want}(-|$|:)" | grep -vE "claude-sonnet-4-5|claude-opus-4-5" | head -n1 || true)
    [[ -n "$candidate" ]] && break
  done
  if [[ -z "$candidate" ]]; then
    warn "$want: no model or inference profile found in $REGION (not available here yet?)"
    continue
  fi
  printf '  %s→%s %s: trying %s ... ' "$BLUE" "$RESET" "$want" "$candidate"
  ERR_FILE=$(mktemp)
  if aws bedrock-runtime converse --profile "$PROFILE" --region "$REGION" --model-id "$candidate" \
       --messages '[{"role":"user","content":[{"text":"Reply with the single word OK."}]}]' \
       --inference-config '{"maxTokens":5}' >/dev/null 2>"$ERR_FILE"; then
    printf '%s✓ access granted%s\n' "$GREEN" "$RESET"
    GRANTED="$GRANTED $candidate"
    case "$want" in
      claude-haiku-4-5) write_env BEDROCK_MODEL_FAST "$candidate" ;;
      claude-sonnet-5)  write_env BEDROCK_MODEL_BALANCED "$candidate" ;;
      claude-opus-5)    write_env BEDROCK_MODEL_ADVANCED "$candidate" ;;
    esac
  else
    printf '%s✗%s\n' "$RED" "$RESET"
    note "$(head -c 300 "$ERR_FILE" 2>/dev/null || true)"
    warn "$want is not usable yet — finish the model-access step, then re-run this wizard."
  fi
  rm -f "$ERR_FILE"
done
if [[ -z "$GRANTED" ]]; then
  SKIPPED+=("Bedrock model access in $REGION (no Claude model answered)")
else
  note "each test call cost a fraction of a cent"
fi
write_env BEDROCK_REGION "$REGION"
pause

# ── 5 ────────────────────────────────────────────────────────────────────
stage "Values the AWS foundation ticket needs"
say "Every AWS resource will be tagged Owner=<you>, and the \$50 Budget emails you."
ask OWNER_TAG "Owner tag value (your name or email):"
ask BUDGET_EMAIL "Email for Budget alerts:"
write_env OWNER_TAG "$OWNER_TAG"
write_env BUDGET_EMAIL "$BUDGET_EMAIL"
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  BODY="Account prerequisites done via scripts/setup-aws-account.sh

- AWS account: ${ACCOUNT_ID}, IAM user: ${USER_NAME} (profile \`${PROFILE}\`, region ${REGION})
- Provisioning rights: $( [[ " $ATTACHED " == *" AdministratorAccess "* ]] && echo AdministratorAccess || echo "see policies attached to the user" )
- Bedrock models answering in ${REGION}:${GRANTED:- none yet}
- Owner tag: ${OWNER_TAG}
- Budget alert email: ${BUDGET_EMAIL}"
  if gh issue comment "$ISSUE" --body "$BODY" >/dev/null 2>&1; then
    printf '  %s✓ commented%s on GitHub issue #%s\n' "$GREEN" "$RESET" "$ISSUE"
  else
    SKIPPED+=("comment on issue #$ISSUE with Owner tag + Budget email")
  fi
else
  SKIPPED+=("comment on issue #$ISSUE with Owner tag + Budget email (gh not ready)")
fi
pause

# ── 6 ────────────────────────────────────────────────────────────────────
stage "Summary"
say "Profile '$PROFILE' → account $ACCOUNT_ID ($USER_NAME), region $REGION"
say "Bedrock models answering:${GRANTED:- none yet}"
say "Owner tag: $OWNER_TAG · Budget email: $BUDGET_EMAIL"
if [[ -n "$GRANTED" ]]; then
  say "Ticket #$ISSUE is complete once the models above all answered — close it, and the"
  say "AWS foundation ticket (#3) can start."
else
  warn "Ticket #$ISSUE stays open until at least one Claude model answers."
fi
pause
finish
